name: flutter_yolo_hyperlpr_plugin
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_yolo_hyperlpr_plugin
        pluginClass: FlutterYoloHyperlprPlugin
      ios:
        pluginClass: FlutterYoloHyperlprPlugin
        
  assets:
   - assets/model/cascade.xml
   - assets/model/CharacterRecognization.caffemodel
   - assets/model/CharacterRecognization.prototxt
   - assets/model/HorizonalFinemapping.caffemodel
   - assets/model/HorizonalFinemapping.prototxt
   - assets/model/SegmenationFree-Inception.caffemodel
   - assets/model/SegmenationFree-Inception.prototxt
   - assets/model/Segmentation.caffemodel
   - assets/model/Segmentation.prototxt